### ISSUE TITLE
似乎cookies更新不了了

### ISSUE THREAD

**Issue by Yun1ng** [Vector000/bilive_client#102]
0|bilive_c | Jun 09 2020 02:48:55 : Error: WebSocket was closed before the connection was established
0|bilive_c |     at WebSocket.close (/root/bilive_client/node_modules/ws/lib/websocket.js:220:14)
0|bilive_c |     at ClientRE.Close (/root/bilive_client/build/lib/client.js:35:24)
0|bilive_c |     at ClientRE._ClientErrorHandler (/root/bilive_client/build/lib/client.js:42:14)
0|bilive_c |     at Timeout.<anonymous> (/root/bilive_client/build/lib/client.js:47:18)
0|bilive_c |     at listOnTimeout (internal/timers.js:531:17)
0|bilive_c |     at processTimers (internal/timers.js:475:7)
0|bilive_c | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|bilive_c | TypeError: Cannot read property 'cookies' of undefined
0|bilive_c |     at Online._update (/root/bilive_client/build/lib/app_client.js:94:54)
0|bilive_c |     at Online.login (/root/bilive_client/build/lib/app_client.js:120:26)
0|bilive_c |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
0|bilive_c |     at async Online._tokenError (/root/bilive_client/build/online.js:129:23)
0|bilive_c |     at async Online.Start (/root/bilive_client/build/online.js:55:22)
0|bilive_c |     at async BiLive.Start (/root/bilive_client/build/index.js:51:28)

**Comment by Yun1ng** [comment]
可以了 似乎是触发了 异地登陆的警告 一直要验证短信
