### ISSUE TITLE
大兄弟 Pm2 了解下？

### ISSUE THREAD

**Issue by StringKe** [Vector000/bilive_client#11]
[https://pm2.io](https://pm2.io)
守护程序，自动更新，热重启

**Comment by abusemydnac** [comment]
pm2 完美解决 重启更新问题,或者线程卡掉线等问题. 但是目前程序需要调整下

pm2 start  ~/bilive_client/build/app.js 


错误信息如下  是否因为路径都是用相对路径的原因.
node ~/bilive_client/build/app.js   [同样错误]
====================================================

> Error: ENOENT: no such file or directory, open '/root/bilive_client/buildbuild/options.default.json'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at new Options (/root/bilive_client/build/options.js:44:50)
    at Object.<anonymous> (/root/bilive_client/build/options.js:91:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

**Comment by ShmilyChen** [comment]
`pm2 start npm --name bilive_client -- start`
一个大佬这样教我的这样，我在服务器上跑没问题

**Comment by Vector000** [comment]
pm2直接运行路径报错 是因为程序里node的start命令行会影响路径的识别，我回头改改
之所以没有搞pm2自动重启/更新，纯粹是因为ts编译的话会有点麻烦（懒），尤其是我目前用树莓派挂机，用tsc-watch编译会快很多

**Comment by BugKun** [comment]
pm2运行路径报错问题，我解决了，已PR，望尽快审核吧
