### ISSUE TITLE
自动更新出现问题

### ISSUE THREAD

**Issue by Huiaei** [Vector000/bilive_client#24]
自动更新出现这些，这要怎么操作啊，大佬？

## 环境
Xiaomi 9 SE _ MIUI 10 _ Android 9
Termux

## 出现的问题

```May 12 2019 11:03:32 : 发现新版本 (master@56abde9f) 10秒后开始更新 可能会重启数次
May 12 2019 11:03:42 : Error: Command failed: git merge
error: Your local changes to the following files would be overwritten by merge:
        bilive/@types/bilive.d.ts
        bilive/lib/tools.ts
        bilive/options.default.json
        bilive/options.ts
        bilive/webapi.ts
        docs/index.html
        docs/options.ts
        docs/script.ts
        package.json
Please commit your changes or stash them before you merge.
Aborting

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Socket.<anonymous> (internal/child_process.js:416:11)
    at Socket.emit (events.js:196:13)
    at Pipe.<anonymous> (net.js:586:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git merge'
}
May 12 2019 11:03:42 : error: Your local changes to the following files would be overwritten by merge:
        bilive/@types/bilive.d.ts
        bilive/lib/tools.ts
        bilive/options.default.json
        bilive/options.ts
        bilive/webapi.ts
        docs/index.html
        docs/options.ts
        docs/script.ts
        package.json
Please commit your changes or stash them before you merge.
Aborting

git pull
Updating ecd01f2..56abde9
error: Your local changes to the following files would be overwritten by merge:
        bilive/@types/bilive.d.ts
        bilive/lib/tools.ts
        bilive/options.default.json
        bilive/options.ts
        bilive/webapi.ts
        docs/index.html
        docs/options.ts
        docs/script.ts
        package.json
Please commit your changes or stash them before you merge.
Aborting

**Comment by Huiaei** [comment]
我是要重装么？

**Comment by Vector000** [comment]
Merge出错，建议先git stash一遍在跑

发送自 Windows 11

________________________________
发件人: ChromeHu <notifications@github.com>
发送时间: Sunday, May 12, 2019 11:22:26 AM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: Re: [Vector000/bilive_client] 自动更新出现问题 (#24)


我是要重装么？

―

**Comment by Huiaei** [comment]
哦，OK，谢谢大佬。
