### ISSUE TITLE
监听错误

### ISSUE THREAD

**Issue by ReginWong** [Vector000/bilive_client#31]
at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

**Comment by ReginWong** [comment]
重连ws服务器失败，一分钟后继续尝试

**Comment by ShmilyChen** [comment]
估计是@lzghzr的服务器炸了，等修复吧，或者自己本地部署[bilive_server](https://github.com/bilive/bilive_server)

**Comment by Vector000** [comment]
监听服务器的域名莫得了[#134](https://github.com/bilive/bilive_client/issues/134)

**Comment by ReginWong** [comment]
> 估计是@lzghzr的服务器炸了，等修复吧，或者自己本地部署[bilive_server](https://github.com/bilive/bilive_server)

哈哈哈不会部署呀~等大大的修复啦

**Comment by ReginWong** [comment]
> 监听服务器的域名莫得了[#134](https://github.com/bilive/bilive_client/issues/134)

那可以直接访问IP？我是真的小白，那服务器那里该填什么呢？

**Comment by AKA-KC** [comment]
部署好了监听哪里应该怎么填写?

**Comment by ShmilyChen** [comment]
ws://服务器ip或者域名:端口#用户子协议
例如本地部署就可以写`ws://localhost:20080#用户子协议`

**Comment by ShmilyChen** [comment]
> 部署好了监听哪里应该怎么填写？

`ws://服务器ip或者域名:端口#用户子协议`
例如本地部署就可以写`ws://localhost:20080#用户子协议`

**Comment by ReginWong** [comment]
我部署成功了，监听服务器有在正常监听，然后在填写“ws://我的IP加端口/#protocol”
是什么原因呢 求解
at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
Jun 14 2019 10:52:42 : 重连ws服务器失败，一分钟后继续尝试



> > 部署好了监听哪里应该怎么填写？
> 
> ws://服务器ip或者域名:端口#用户子协议
> 例如本地部署就可以写ws://localhost:20080#用户子协议

**Comment by ReginWong** [comment]
部署成功了，监听也正常，但推过来的时候只有几个正常，有的会报错：
 at ClientRequest.req.on (/test/A/node_modules/ws/lib/websocket.js:595:7)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)

求解！！


> > 部署好了监听哪里应该怎么填写？
> 
> `ws://服务器ip或者域名:端口#用户子协议`
> 例如本地部署就可以写`ws://localhost:20080#用户子协议`

**Comment by ReginWong** [comment]
自己部署的，有的房间号是错的？

**Comment by ReginWong** [comment]
部署√ 问题已解决

不过有一个想反馈
本地监听的话只有部分小电视或大厦
没有舰队节奏风暴

**Comment by Vector000** [comment]
这个其实不是问题…因为本地监听没法监听舰队和节奏，除非监听几千个房间

发送自 Windows 11

________________________________
发件人: ReginWong <notifications@github.com>
发送时间: Friday, June 14, 2019 6:58:46 PM
收件人: Vector000/bilive_client
抄送: Vector000; Comment
主题: Re: [Vector000/bilive_client] 监听错误 (#31)


部署√ 问题已解决

不过有一个想反馈
本地监听的话只有部分小电视或大厦
没有舰队节奏风暴

―

**Comment by lzghzr** [comment]
因为默认是不提供节奏和舰队的吧(太长时间我有点忘了
________________________________

**Comment by zanewayne78** [comment]
@lzghzr 怎么解决刚开启服务端的roomlist高并发问题，把我的宽带都搞掉线了

**Comment by lzghzr** [comment]
这个我倒是没考虑过，我记得当时有人反应家宽跑起来以后网络基本没法用，服务器上倒是很流畅
________________________________

**Comment by Vector000** [comment]
家宽跑起来网络直接爆破，而且效果也不好，不清楚是网卡的原因还是运营商宽带的锅
用服务器的话过万房间都能监听

发送自 Windows 11

________________________________
发件人: lzghzr <notifications@github.com>
发送时间: Saturday, June 15, 2019 2:23:10 PM
收件人: Vector000/bilive_client
抄送: Vector000; Comment
主题: Re: [Vector000/bilive_client] 监听错误 (#31)

这个我倒是没考虑过，我记得当时有人反应家宽跑起来以后网络基本没法用，服务器上倒是很流畅
________________________________

**Comment by zanewayne78** [comment]
难道只能用服务器跑？😞

**Comment by AKA-KC** [comment]
Jun 15 2019 20:52:24 : Error: getaddrinfo ENOTFOUND chuan.topvj100.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'chuan.topvj100.com'


服务器上跑了跑~出现这个问题
